---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - role[sysadmins]
      - recipe[kedpm-transit::default]
      - recipe[kedpm-transit-test::default]
    attributes: { kedpm: { shared-dir: "/root/passwords/" } }
