#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'kedpm-transit',
  :path => '.'

cookbook 'kedpm',
  :github => 'umts/chef-kedpm'

cookbook 'rsnapshot',
  :github => 'umts/rsnapshot'

cookbook 'users'
